spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./h2/testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
